conda install pytorch=1.0.1 torchvision=0.2.2 cudatoolkit=10.0 -c pytorch
pip install tensorflow==1.14.0
pip install scipy==1.3.0
pip install pillow==6.1.0
pip install ipython==7.7.0
pip install numpy==1.16.4

